### ISSUE TITLE
"lang" attribute always set to "en" on first page load

### ISSUE THREAD

**Issue by pcraig3** [DTS-STN/Alpha-Site#83]
We have actually done a lot of things right here. We have included a `lang` tag on our `<html>` element, and we _are_ changing it between "en" and "fr" as we change the language using the link at the top of the page.

However, if we load the landing page in French (https://alphasite-main.dev.dts-stn.com/fr), it defaults to `lang="en"`, which is wrong. It should say `lang="fr"` when we request a french version of the site.

This was also [flagged by the HTML validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Falphasite-main.dev.dts-stn.com%2Ffr).

**Comment by will0684** [comment]
Ok yeah I see what you mean. 

My PR [here](https://github.com/DTS-STN/Alpha-Site/pull/86) makes it so that when you visit the page, regardless of the locale in the URL you enter, it will check the language you have in localstorage and navigate you to the page with the appropriate locale _as well as_ set the locale for the whole application, which changes the html lang attribute to match.

**Comment by will0684** [comment]
#86 may address this issue if you would like to confirm it meets our needs @pcraig3. I believe it does.

**Comment by Moro-Code** [comment]
Closing since #86 is merged

**Comment by pcraig3** [comment]
Yup, all good here. Tried the validator again and the error is gone. Thanks @will0684!
