### ISSUE TITLE
Skip to content link not appearing on dev deployment

### ISSUE THREAD

**Issue by will0684** [DTS-STN/Alpha-Site#99]
The "Skip to Content" link is not showing up on the deployed website.

**Comment by var-kyle** [comment]
The build in TeamCity says it was successful, but it is also giving this warning in the deploy step:

`WARNING: No credential was provided to access Azure Container Registry. Trying to look up...`

Since we're moving the pipeline to ADO, is it worth fixing here, or just waiting until ADO is up and running? @blai0264 should know how the pipeline in ADO is coming along.

**Comment by blai0264** [comment]
Working on the ADO pipeline right now. Im able to successfully deploy the API through ADO with no issues (because it has no build . However, when trying to deploy the Admin application I cannot get the value of STRAPI_BACKEND_API_URL to resolve to the proper url of the deployed API. There seems to be an issue injecting environment variables to the container through the ADO pipeline. Which is odd because this works fine in the Teamcity pipeline. I'm assuming this will be an issue when I try to setup the Alpha Site pipeline as well. Working on figuring it out right now ill keep you guys posted.

**Comment by will0684** [comment]
This was a problem with Alpha Site at our previous URL but at the new URL https://alphasite.dts-stn.com/ , this is no longer an issue.
